version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dezurechallenge
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin7*
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - ./src/infra/db/servers.json:/pgadmin4/servers.json